### ISSUE TITLE
2017 Cake Party

### ISSUE THREAD

**Issue by nebgnahz** [nebgnahz/blog#13]
### Details

**Time**: Sunday, 03/12, 5:30pm
**Place**: Ben's place, 3995 Adeline Street, Emeryville, CA

---
### Cakes and Baking Goods

- [ ] Green Tea Thousand-layer Cake （抹茶千层蛋糕）
- [x] New York Cheesecake （纽约芝士蛋糕）
- [x] <s>Sourdough Bread（酸麵麵糰面包，starter 没养好）</s>
- [ ] Cookie

---
### 菜 (tentative)

- [x] 凉菜，木耳
- [x] 凉菜，白切鸡
- [x] 凉菜，自制 Kimchi
- [x] 热素菜，手撕包菜
- [x] 热素菜，白灼芥蓝
- [x] 热菜，豉油鸡（金阁）
- [x] 热荤菜，味噌三文鱼
- [x] 热荤菜，烤鱼
- [x] 热荤菜，红烧排骨
- [x] 热汤，腌笃鲜
- [ ] 米饭？
- [x] 酒 (XJ)

**Comment by pxgao** [comment]
赞
