### ISSUE TITLE
2017 Pittsburgh Visit

### ISSUE THREAD

**Issue by nebgnahz** [nebgnahz/blog#16]
## Time

11/30 (Thursday) 10:30pm -- 12/04 (Monday) 3:00pm

### Friday
- [x] Gates Hillman Centers (GHC)
- [x] Cathedral of Learning (Nationality rooms)

### Saturday
- [x] Three Rivers Heritage Trail
- [x] House Poem & City of Asylum (daytime)
- [x] <s>Bicycle Heaven (10AM to 7PM)</s>
- [x] Mattress Factory (2-3 tour, 1-4 artlab)
- [x] Lunch at Gaucho Parrilla Argentina
- [x] The Andy Warhol Museum (closed on Monday, Photographic at 1pm, 11am/3pm gallery talks)
- [x] <s>Fort Pitt Museum (10 a.m. to 5 p.m.)</s>
- [x] Mt Washington (Sunset 4:55pm)

### Sunday
- [x] Falling Water (SE direction, near Ohiopyle State Park)
- [x] Ohiopyle State Park
- [x] Phipps Conservatory and Botanical Gardens (9:30 a.m. – 11 p.m.)

### Monday
- [x] Others...

## Food

- [x] [Fri Lunch] [Everyday Noodles (天天见面）](http://www.everydaynoodles.net/)
- [x] [Fri Dinner] Chengdu Gourmet
- [x] [Sat Lunch] Gaucho Parrilla Argentina
- [x] [Sat Dinner] Jade Grille
- [x] [Sun Brunch] La Gourmandine
- [x] [Sun Dinner] Church Brew Works
- [x] <s>Bread and Salt Bakery (permanently closed)</s>
- [x] <s>Arsenal Cider House</s>
- [x] <s>Wild mushrooms at Wild Purveyors</s>
- [x] <s>hofbräuhaus pittsburgh</s>

## Guides

- [NYT](https://www.nytimes.com/2015/07/19/travel/what-to-do-in-36-hours-in-pittsburgh.html)
- [豆瓣](https://www.douban.com/note/513988839/)

## Weather Forecast

Day | DESCRIPTION | TEMP | PRECIP | WIND | HUMIDITY
-- | -- | -- | -- | -- | --
THU NOV 30 | PM Showers | 15°/1° | 60% | SSW 16 km/h | 55%
FRI DEC 1 | Partly Cloudy | 8°/-1° | 10% | NW 6 km/h | 65%
SAT DEC 2 | Partly Cloudy | 10°/1° | 10% | S 6 km/h | 60%
SUN DEC 3 | Partly Cloudy | 10°/1° | 10% | W 9 km/h | 63%
MON DEC 4 | Mostly Cloudy | 13°/8° | 10% | SE 12 km/h | 56%

## Transportation

[28X AIRPORT FLYER](http://portauthority.org/rt/28X.pdf)

**From**: Pgh Intl Airport, Arrivals-Lower Level, Door 6 
**To**: Oakland-CMU, Forbes Ave, past Morewood Ave
**Time**: <s>10:30--11:24</s> or 11:00--11:54 or 11:30--12:24

**Comment by zhuoc** [comment]
吃的还有
Gaucho Parrilla Argentina
hofbräuhaus pittsburgh
中餐的话我就随意发挥了：）
