### ISSUE TITLE
2016 Merry Christmas Hotpot

### ISSUE THREAD

**Issue by nebgnahz** [nebgnahz/blog#6]
时间
---
12/21/2016 6:00pm

Host
---
![img_3090](https://cloud.githubusercontent.com/assets/941519/21302168/63ebb480-c569-11e6-98c9-da7d2f0ccc7a.JPG)

地点
---
Ben's Home

停车场位置：[3965 Adeline Street, Oakland, CA](https://goo.gl/maps/kzanF12A2Nv)。注意停车场里没信号，提前三分钟联系我，我下楼去接。

食物
---
- 火锅 （麻辣锅和参鸡汤锅）
- [煲仔饭](https://cloud.githubusercontent.com/assets/941519/21170025/41379784-c176-11e6-800c-658b72c95db1.JPG)
- 酒，[cocktail](https://github.com/nebgnahz/blog/blob/master/posts/cocktail.md) 里写了我会做的，其他的提前说，我可以学习学习。
- 其他小菜？

购买清单
---
- [x] 麻辣火锅底料 (YT)
- [x] 牛肉 (BZ)
- [x] 羊肉 (BZ)
- [x] 牛舌 (BZ)
- [x] 黄喉 (BZ)
- [x] 牛百叶 (BZ)
- [x] 鱼豆腐 (BZ)
- [x] 午餐肉 (BZ)
- [x] 丸子 (KF+YZ)
- [x] 香油 (KF+YZ)
- [x] 芝麻酱 (KF+YZ)
- [x] 蘑菇 (KF+YZ)
- [x] 萝卜(KF+YZ)
- [x] 土豆 (KF+YZ)
- [x] 豆腐 (KF+YZ)
- [x] 葱 (KF+YZ)
- [x] 腐竹 (KF+YZ)
- [x] 水果 (PH)
- [x] 饮料 (CR)

花费
---
- 肉: 42.67
- 水果 + 饮料：28.9
- 蔬菜：?
- 蛋糕：31

**Comment by kaifeichen** [comment]
```
md用的很溜啊
```

**Comment by nebgnahz** [comment]
> 无他，唯手熟耳
